version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.4

jobs:
  deploy-develop:
    working_directory: ~/workspace
    docker:
      - image: google/cloud-sdk:latest

    steps:
      - checkout
      - run:
          name: SetUp
          command: |
              echo "  PRIVATE_KEY: $PRIVATE_KEY" >> app.yaml
      - gcp-cli/initialize
      - run:
          name: Deploy to Google App Engine
          command: |
            gcloud app --quiet deploy ./app.yaml --project=$GOOGLE_PROJECT_ID

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-develop
